Algoritmo "ex_01"
// Disciplina   : [Lógica de Programação]
// Professor   : Willian Ribeiro de Souza Paulino
// Descrição   :  Crie um algoritmo que mostre na tela a mensagem: Estou criando meu primeiro código


// Autor(a)    : Rayane Cristiana Barbosa
// Data atual  : 22/02/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Estou criando meu primeiro código")



Fimalgoritmo