# -*- coding: utf-8 -*-
"""Ex_01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nANMYHIq3pcuxZhVyRGZ-lYKuBgCbYvW
"""

#Solicite ao usuário a entrada de um valor para a variável “contador”, somar 10 unidades à variável e mostrar o resultado



contador = int(input("Digite um numero: "))

print("Resultado: ", contador + 10)